apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: %WORKLOAD%-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/varianter/infrastructure-as-code
    targetRevision: HEAD
    path: deployments/dev/workloads/%WORKLOAD%
    # Values are now fetched from the cluster-config ConfigMap by the Helm chart
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
