apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: %WORKLOAD%-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/varianter/infrastructure-as-code
    targetRevision: HEAD
    path: deployments/prod/workloads/%WORKLOAD%
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
